---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/raxelpichardo/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R /home4/raxelpichardo/repositories/css $DEPLOYPATH
    - /bin/cp -R /home4/raxelpichardo/repositories/js $DEPLOYPATH
    - /bin/cp -R /home4/raxelpichardo/repositories/img $DEPLOYPATH