---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/nues/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R /home4/nues/repositories/Boda/css $DEPLOYPATH
    - /bin/cp -R /home4/nues/repositories/Boda/js $DEPLOYPATH
    - /bin/cp -R /home4/nues/repositories/Boda/img $DEPLOYPATH